{
 "title": "abcd",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kitex_server_throughput{status=\"succeed\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "current goroutines",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "avg gc count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service)(rate(go_gc_duration_seconds_count{}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "server latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(service,method)(rate(kitex_server_latency_us_sum[1m]))/sum by(service,method)(rate(kitex_server_latency_us_count[1m]))",
     "legendFormat": "{{service}}-{{method}}"
    }
   ]
  },
  {
   "title": "95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kitex_server_latency_us_bucket[1m])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kitex_server_latency_us_bucket[1m])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "memstats alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(service)(go_memstats_alloc_bytes{})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "avg goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    { "expr": "avg by(service)(go_goroutines)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "memstats heap alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(service)(go_memstats_heap_alloc_bytes{})",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}